name: head_start
description: "Quick Start Template for Flutter projects with various widget - plugins."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI #
  cupertino_icons: ^1.0.2 # Default by Flutter
  animated_text_kit: ^4.2.2 # For animated titles or texts
  lottie: ^2.7.0 # For animation / icons
  smooth_page_indicator: ^1.1.0 # For introduction Screen
  animated_splash_screen: ^1.3.0 # For splash screen
  google_fonts: ^6.1.0 # For fonts

  # Backend #
  dio: ^5.4.0 # For API calls
  http: ^1.1.2 # For API calls
  hive: ^2.2.3 # Local DB
  shared_preferences: ^2.2.2 # LocalDB
  shimmer: ^3.0.0 # For loading animation
  easy_localization: ^3.0.3 # For multi language support
  

# DEV #
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/ # Images
    - assets/translations/ # Translations
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700